ElectionDate = new Date(2021,2,13)
ElectionDateStr = ElectionDate.toDateString();


RawDataHeaderID = [
  "N/A",  "N/A",  "N/A",  
  "ALP", 
  "Lib",
  "Nat",
  "Grn",
  "One",
  "Oth",
  "N/A","N/A",  "N/A" 
]

PollList = [
  "Lib",
  "Nat",
  "ALP",
  "Grn",
  "One",
  "UAP",
  "Oth",
  ]

Location = {
  "ALP":3,
  "ALP2PP":9,
  "Lib":4,
  "Lib2PP":10,
  "Nat":5,
  "Grn":6,
  "One":7,
  "Oth":8,
}

var PollIDConvert = {
  "ALP": "ALP",
  "Lib": "Lib",
  "LaP": "Lib",
  "LNP": "Lib",
  "UAP": "UAP",
  "Grn": "Grn", 
  "Nat": "Nat",
  "One": "One",
  "Oth": "Oth",
  "Ind": "Oth",
  "JLN": "Oth",
  "CAl": "Oth",
  "KAP": "Oth"
}
 
var PartyNameArray = {
  "ALP": "Labor Party",
  "Lib": "Liberal Party",
  "LaP": "Liberal and Nationals Party",
  "LNP": "Liberal National Party",
  "UAP": "United Australia Party",
  "Grn": "Greens", 
  "Nat": "Nationals",
  "One": "One Nation",
    "Oth": "Other",
  "Ind": "Indipendent",
  "JLN": "Jacqui Lambie Network",
  "CAl": "Center Alliance",
  "KAP": "Katter Australia Party"
}

var PartyColor = {
  "ALP": "#ee0003",
  "Lib": "#0068e8",
  "LaP": "#0068e8",
  "LNP": "#008fe8",
  "UAP": "#ffff00",
  "Grn": "#33b747", 
  "Nat": "#1f412f",
  "One": "#cc5b10",
    "Oth": "#EDE7E3",
  "Ind": "#C2C7D0",
  "JLN": "#BCA371",
  "CAl": "Orange",
  "KAP": "#910f00"
}

ElectorateList = [
"Albany",
"Armadale",
"Balcatta",
"Baldivis",
"Bassendean",
"Bateman",
"Belmont",
"Bicton",
"Bunbury",
"BurnsBeach",
"Butler",
"Cannington",
"Carine",
"CentralWheatbelt",
"Churchlands",
"Cockburn",
"ColliePreston",
"Cottesloe",
"DarlingRange",
"Dawesville",
"Forrestfield",
"Fremantle",
"Geraldton",
"Hillarys",
"Jandakot",
"Joondalup",
"Kalamunda",
"Kalgoorlie",
"Kimberley",
"Kingsley",
"Kwinana",
"Landsdale",
"Mandurah",
"Maylands",
"Midland",
"Mirrabooka",
"Moore",
"Morley",
"MountLawley",
"MurrayWellington",
"Nedlands",
"NorthWestCentral",
"Perth",
"Pilbara",
"Riverton",
"Rockingham",
"Roe",
"Scarborough",
"SouthPerth",
"SouthernRiver",
"SwanHills",
"Thornlie",
"Vasse",
"VictoriaPark",
"Wanneroo",
"Warnbro",
"WarrenBlackwood",
"WestSwan",
"Willagee"
]

var ElectorateIDNameArray = {
  'Albany':'Albany',
  'Armadale':'Armadale',
  'Balcatta':'Balcatta',
  'Baldivis':'Baldivis',
  'Bassendean':'Bassendean',
  'Bateman':'Bateman',
  'Belmont':'Belmont',
  'Bicton':'Bicton',
  'Bunbury':'Bunbury',
  'BurnsBeach':'Burns Beach',
  'Butler':'Butler',
  'Cannington':'Cannington',
  'Carine':'Carine',
  'CentralWheatbelt':'Central Wheatbelt',
  'Churchlands':'Churchlands',
  'Cockburn':'Cockburn',
  'ColliePreston':'Collie-Preston',
  'Cottesloe':'Cottesloe',
  'DarlingRange':'Darling Range',
  'Dawesville':'Dawesville',
  'Forrestfield':'Forrestfield',
  'Fremantle':'Fremantle',
  'Geraldton':'Geraldton',
  'Hillarys':'Hillarys',
  'Jandakot':'Jandakot',
  'Joondalup':'Joondalup',
  'Kalamunda':'Kalamunda',
  'Kalgoorlie':'Kalgoorlie',
  'Kimberley':'Kimberley',
  'Kingsley':'Kingsley',
  'Kwinana':'Kwinana',
  'Landsdale':'Landsdale',
  'Mandurah':'Mandurah',
  'Maylands':'Maylands',
  'Midland':'Midland',
  'Mirrabooka':'Mirrabooka',
  'Moore':'Moore',
  'Morley':'Morley',
  'MountLawley':'Mount Lawley',
  'MurrayWellington':'Murray-Wellington',
  'Nedlands':'Nedlands',
  'NorthWestCentral':'North West Central',
  'Perth':'Perth',
  'Pilbara':'Pilbara',
  'Riverton':'Riverton',
  'Rockingham':'Rockingham',
  'Roe':'Roe',
  'Scarborough':'Scarborough',
  'SouthPerth':'South Perth',
  'SouthernRiver':'Southern River',
  'SwanHills':'Swan Hills',
  'Thornlie':'Thornlie',
  'Vasse':'Vasse',
  'VictoriaPark':'Victoria Park',
  'Wanneroo':'Wanneroo',
  'Warnbro':'Warnbro',
  'WarrenBlackwood':'Warren-Blackwood',
  'WestSwan':'West Swan',
  'Willagee':'Willagee',
}

var Currentelectorateparty = {
'Albany':'ALP',
'Armadale':'ALP',
'Balcatta':'ALP',
'Baldivis':'ALP',
'Bassendean':'ALP',
'Bateman':'ALP',
'Belmont':'ALP',
'Bicton':'ALP',
'Bunbury':'ALP',
'BurnsBeach':'ALP',
'Butler':'ALP',
'Cannington':'ALP',
'Carine':'ALP',
'CentralWheatbelt':'Nat',
'Churchlands':'ALP',
'Cockburn':'ALP',
'ColliePreston':'ALP',
'Cottesloe':'Lib',
'DarlingRange':'ALP',
'Dawesville':'ALP',
'Forrestfield':'ALP',
'Fremantle':'ALP',
'Geraldton':'ALP',
'Hillarys':'ALP',
'Jandakot':'ALP',
'Joondalup':'ALP',
'Kalamunda':'ALP',
'Kalgoorlie':'ALP',
'Kimberley':'ALP',
'Kingsley':'ALP',
'Kwinana':'ALP',
'Landsdale':'ALP',
'Mandurah':'ALP',
'Maylands':'ALP',
'Midland':'ALP',
'Mirrabooka':'ALP',
'Moore':'Nat',
'Morley':'ALP',
'MountLawley':'ALP',
'MurrayWellington':'ALP',
'Nedlands':'ALP',
'NorthWestCentral':'Lib',
'Perth':'ALP',
'Pilbara':'ALP',
'Riverton':'ALP',
'Rockingham':'ALP',
'Roe':'Nat',
'Scarborough':'ALP',
'SouthPerth':'ALP',
'SouthernRiver':'ALP',
'SwanHills':'ALP',
'Thornlie':'ALP',
'Vasse':'Lib',
'VictoriaPark':'ALP',
'Wanneroo':'ALP',
'Warnbro':'ALP',
'WarrenBlackwood':'ALP',
'WestSwan':'ALP',
'Willagee':'ALP',
}

var ElcLocation = {}
var StateIDArray = {};
var MPArray = {};
